//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTONSPARPALETTE
    {
        public decimal IDCARTONPALETTE { get; set; }
        public decimal NBCARTONPPALETTE { get; set; }
        public decimal IDTRANSPORT { get; set; }
    
        public virtual TRANSPORTS TRANSPORTS { get; set; }
    }
}
