//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDITIONNEMENT
    {
        public CONDITIONNEMENT()
        {
            this.LIGNESCOMMANDES = new HashSet<LIGNESCOMMANDES>();
        }
    
        public decimal IDMACHINECONDI { get; set; }
        public string NOMMACHINECONDI { get; set; }
        public decimal CADENCEMACHINECONDI { get; set; }
        public decimal DELAIMACHINECONDI { get; set; }
        public decimal IDCONTENANT { get; set; }
    
        public virtual CONTENANTS CONTENANTS { get; set; }
        public virtual ICollection<LIGNESCOMMANDES> LIGNESCOMMANDES { get; set; }
    }
}
