//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BONBONS> BONBONS { get; set; }
        public virtual DbSet<CARTONSPARPALETTE> CARTONSPARPALETTE { get; set; }
        public virtual DbSet<COMMANDES> COMMANDES { get; set; }
        public virtual DbSet<CONDITIONNEMENT> CONDITIONNEMENT { get; set; }
        public virtual DbSet<CONTENANTS> CONTENANTS { get; set; }
        public virtual DbSet<CONTENANTSPARCARTON> CONTENANTSPARCARTON { get; set; }
        public virtual DbSet<COULEURS> COULEURS { get; set; }
        public virtual DbSet<FABRICATION> FABRICATION { get; set; }
        public virtual DbSet<LIGNESCOMMANDES> LIGNESCOMMANDES { get; set; }
        public virtual DbSet<PAYS> PAYS { get; set; }
        public virtual DbSet<PRIX> PRIX { get; set; }
        public virtual DbSet<TEXTURES> TEXTURES { get; set; }
        public virtual DbSet<TRANSPORTS> TRANSPORTS { get; set; }
        public virtual DbSet<VARIANTES> VARIANTES { get; set; }
    }
}
