//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FABRICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FABRICATION()
        {
            this.LIGNESCOMMANDES = new HashSet<LIGNESCOMMANDES>();
        }
    
        public decimal IDMACHINEFAB { get; set; }
        public string NOMMACHINEFAB { get; set; }
        public decimal CADENCEMACHINEFAB { get; set; }
        public decimal DELAIMACHINEFAB { get; set; }
        public decimal IDVARIANTE { get; set; }
    
        public virtual VARIANTES VARIANTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNESCOMMANDES> LIGNESCOMMANDES { get; set; }
    }
}
