//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIGNESCOMMANDES
    {
        public decimal IDCONTENUCOMMANDE { get; set; }
        public decimal NBCONTENANTS { get; set; }
        public Nullable<decimal> TEMPSFAB { get; set; }
        public Nullable<decimal> TEMPSCONDI { get; set; }
        public decimal IDCOMMANDE { get; set; }
        public decimal IDCONTENANT { get; set; }
        public decimal IDBONBON { get; set; }
        public decimal IDVARIANTE { get; set; }
        public decimal IDTEXTURE { get; set; }
        public decimal IDCOULEUR { get; set; }
        public Nullable<decimal> IDMACHINEFAB { get; set; }
        public Nullable<decimal> IDMACHINECONDI { get; set; }
    
        public virtual BONBONS BONBONS { get; set; }
        public virtual COMMANDES COMMANDES { get; set; }
        public virtual CONDITIONNEMENT CONDITIONNEMENT { get; set; }
        public virtual CONTENANTS CONTENANTS { get; set; }
        public virtual COULEURS COULEURS { get; set; }
        public virtual FABRICATION FABRICATION { get; set; }
        public virtual TEXTURES TEXTURES { get; set; }
        public virtual VARIANTES VARIANTES { get; set; }
    }
}
