//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BONBONS> BONBONS { get; set; }
        public DbSet<COMMANDES> COMMANDES { get; set; }
        public DbSet<CONDITIONNEMENT> CONDITIONNEMENT { get; set; }
        public DbSet<CONTENANTS> CONTENANTS { get; set; }
        public DbSet<COULEURS> COULEURS { get; set; }
        public DbSet<LIGNESCOMMANDES> LIGNESCOMMANDES { get; set; }
        public DbSet<PAYS> PAYS { get; set; }
        public DbSet<TEXTURES> TEXTURES { get; set; }
        public DbSet<TRANSPORTS> TRANSPORTS { get; set; }
        public DbSet<VARIANTES> VARIANTES { get; set; }
    }
}
