//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYS
    {
        public PAYS()
        {
            this.COMMANDES = new HashSet<COMMANDES>();
        }
    
        public decimal IDPAYS { get; set; }
        public string NOMPAYS { get; set; }
        public decimal IDTRANSPORT { get; set; }
    
        public virtual ICollection<COMMANDES> COMMANDES { get; set; }
        public virtual TRANSPORTS TRANSPORTS { get; set; }
    }
}
