//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTS
    {
        public TRANSPORTS()
        {
            this.PAYS = new HashSet<PAYS>();
        }
    
        public decimal IDTRANSPORT { get; set; }
        public string NOMTRANSPORT { get; set; }
        public decimal COUTTRANSPORT { get; set; }
        public decimal CONTENANCETRANSPORT { get; set; }
    
        public virtual ICollection<PAYS> PAYS { get; set; }
    }
}
