--------------------------------------------------------
--  TABLE CONDITIONNEMENT
--------------------------------------------------------

Insert into CONDITIONNEMENT (NOMMACHINECONDI,CADENCEMACHINECONDI,DELAIMACHINECONDI,IDCONTENANT) values ('1','500','15','1');
Insert into CONDITIONNEMENT (NOMMACHINECONDI,CADENCEMACHINECONDI,DELAIMACHINECONDI,IDCONTENANT) values ('2','500','15','1');
Insert into CONDITIONNEMENT (NOMMACHINECONDI,CADENCEMACHINECONDI,DELAIMACHINECONDI,IDCONTENANT) values ('3','750','25','1');
Insert into CONDITIONNEMENT (NOMMACHINECONDI,CADENCEMACHINECONDI,DELAIMACHINECONDI,IDCONTENANT) values ('4','200','10','2');
Insert into CONDITIONNEMENT (NOMMACHINECONDI,CADENCEMACHINECONDI,DELAIMACHINECONDI,IDCONTENANT) values ('5','200','10','2');
Insert into CONDITIONNEMENT (NOMMACHINECONDI,CADENCEMACHINECONDI,DELAIMACHINECONDI,IDCONTENANT) values ('6','150','15','3');

