--------------------------------------------------------
--  TABLE FABRICATION   
--------------------------------------------------------

Insert into FABRICATION (NOMMACHINEFAB,CADENCEMACHINEFAB,DELAIMACHINEFAB,IDVARIANTE) values ('1','750','25','1');
Insert into FABRICATION (NOMMACHINEFAB,CADENCEMACHINEFAB,DELAIMACHINEFAB,IDVARIANTE) values ('2','1230','45','2');
Insert into FABRICATION (NOMMACHINEFAB,CADENCEMACHINEFAB,DELAIMACHINEFAB,IDVARIANTE) values ('3','625','25','3');
Insert into FABRICATION (NOMMACHINEFAB,CADENCEMACHINEFAB,DELAIMACHINEFAB,IDVARIANTE) values ('4','1230','45','2');
Insert into FABRICATION (NOMMACHINEFAB,CADENCEMACHINEFAB,DELAIMACHINEFAB,IDVARIANTE) values ('5','625','25','3');

